# Generated by Django 5.1.6 on 2025-04-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0151_alter_new_user_enquiry_clg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=10),
        ),
    ]
