# Generated by Django 5.1.6 on 2025-04-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0152_alter_jobseeker_resume_phone_alter_resume_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=10),
        ),
    ]
