# Generated by Django 5.1.6 on 2025-04-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0153_alter_college_phone_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobseeker_resume',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
