# Generated by Django 5.1.5 on 2025-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_alter_universityincharge_clg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionreview1',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
