# Generated by Django 5.1.5 on 2025-04-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_companyincharge_is_online_consultant_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='mode_study',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='preferred_destination',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='user_type',
        ),
    ]
