# Generated by Django 5.1.5 on 2025-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_remove_new_user_course_remove_new_user_educations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user',
            name='course',
            field=models.CharField(default='B-Tech', max_length=50),
        ),
        migrations.AddField(
            model_name='new_user',
            name='educations',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AddField(
            model_name='new_user',
            name='entrance',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='new_user',
            name='mode_study',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='new_user',
            name='passport',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AddField(
            model_name='new_user',
            name='percentage',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='new_user',
            name='preferred_destination',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AddField(
            model_name='new_user',
            name='start_date',
            field=models.CharField(default='2025', max_length=4),
        ),
        migrations.AddField(
            model_name='new_user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('job_seeker', 'Job Seeker')], default='student', max_length=20),
        ),
    ]
