# Generated by Django 5.1.5 on 2025-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_messageattachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinestatus',
            name='user',
        ),
        migrations.AddField(
            model_name='onlinestatus',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
    ]
