# Generated by Django 5.1.5 on 2025-04-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_onlinestatus_user_onlinestatus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
